name: Pavlo_polyak_25021982
env:
 PACK_NAME: "docker ${{ github.sha }}"
 APP_NAME: "Docker"
 
on:
  push:
    branches: 
      - Pavlo_polyak_25021982
  pull_request:
    branches: 
      - Pavlo_polyak_25021982
  workflow_dispatch:

jobs:
  my_ubuntu:
    runs-on: ubuntu-latest 
    steps:
      
    - name: git clone
      uses: actions/checkout@v1

    - name: wokr dir
      run: cd /USPN

    - name: print ls
      run: ls -lsa
      
  my_python:
    runs-on: ubuntu-latest
    needs: [my_ubuntu]
    strategy:
      matrix:
        python-version:
        - 'pypy-3.6' # the latest available version of PyPy that supports Python 3.6
#         - 'pypy-3.7' # the latest available version of PyPy that supports Python 3.7
#         - 'pypy-3.7-v7.3.3' # Python 3.7 and PyPy 7.3.3
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        pip install paramiko
        pip install pandas
        pip install sqlalchemy
        pip install openpyxl
        python sql_orm.py
        
